# Generated by Django 5.2.7 on 2026-01-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commun', models.CharField(max_length=100)),
                ('nom_savant', models.CharField(max_length=150)),
                ('embranchement', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=100)),
                ('ordre', models.CharField(max_length=100)),
                ('sous_ordre', models.CharField(blank=True, max_length=100)),
                ('famille', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('statut_iucn', models.CharField(choices=[('LC', 'Préoccupation mineure'), ('NT', 'Quasi menacé'), ('VU', 'Vulnérable'), ('EN', 'En danger'), ('CR', 'En danger critique'), ('DD', 'Données insuffisantes')], max_length=5)),
                ('description', models.TextField()),
            ],
        ),
    ]
