# Generated by Django 6.0.1 on 2026-01-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
