# Generated by Django 5.2.7 on 2026-01-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observo', '0003_observ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='observ',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
