# Generated by Django 6.0.1 on 2026-01-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observo', '0004_alter_animal_id_alter_observ_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observ',
            old_name='description_t',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='animal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='observ',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
