# Generated by Django 6.0.1 on 2026-01-09 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observo', '0008_observ_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='observ',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Confiance IA (%)'),
        ),
        migrations.AddField(
            model_name='observ',
            name='ai_detected_species',
            field=models.CharField(blank=True, max_length=150, verbose_name='Espèce détectée par IA (simulation)'),
        ),
        migrations.AddField(
            model_name='observ',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='observations/%Y/%m/%d/', verbose_name="Photo de l'observation"),
        ),
        migrations.AlterField(
            model_name='observ',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observo.animal', verbose_name='Animal observé'),
        ),
        migrations.AlterField(
            model_name='observ',
            name='date_heure',
            field=models.DateTimeField(verbose_name='Date et heure'),
        ),
        migrations.AlterField(
            model_name='observ',
            name='description',
            field=models.TextField(verbose_name="Description de l'observation"),
        ),
        migrations.AlterField(
            model_name='observ',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='observ',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='observ',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL, verbose_name='Observateur'),
        ),
    ]
